# Generated by Django 5.0.7 on 2024-07-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('guides', '0001_initial'),
        ('tours', '0003_tours_max_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('booking_date', models.DateField()),
                ('tour_date', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], max_length=20)),
                ('special_requests', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.customers')),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='guides.guides')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tours')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-tour_date'],
                'indexes': [models.Index(fields=['tour_date'], name='tour_date_idx'), models.Index(fields=['booking_date'], name='booking_date_idx')],
            },
        ),
    ]
