# Generated by Django 5.0.7 on 2024-07-15 08:17

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'easy'), ('moderate', 'moderate'), ('challenging', 'challenging'), ('challenging', 'challenging'), ('extreme', 'extreme')], max_length=100)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('included', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=100)),
                ('not_included', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=100)),
                ('meeting_point', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tours',
                'db_table': 'tours',
                'ordering': ['-duration'],
            },
        ),
    ]
