# Generated by Django 5.0.7 on 2024-07-15 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tours_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='max_participants',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
            preserve_default=False,
        ),
    ]
